name: Crystal CI

on:
  push:
    branches: [ "main" , "ci"]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 19 * * SAT"

jobs:
  check_format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Format
        run: crystal tool format --check

  coding_standards:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: shards install
      - name: Ameba
        run: ./bin/ameba
  test_latest:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: shards build --production
      - name: Specs
        run: crystal spec --error-on-warnings --verbose
  test_nightly:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:nightly-alpine
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: shards build --production
      - name: Specs
        run: crystal spec --error-on-warnings --verbose
  deploy_docs:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - name: Install Build Dependencies
        run: apk add --update rsync
      - uses: actions/checkout@v3
      - name: Build
        run: crystal docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: docs
          SINGLE_COMMIT: true
