name: Crystal CI

on:
  push:
    branches: [ "main" , "ci"]
  pull_request:
    branches: [ "main" ]

jobs:
  spec:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Run format
      run: crystal tool format --check
  
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - name: shards build
      run: shards build --release --no-debug --production
